Update pipeline with K neighbours & Add classification with NN
SmirnovOleg/bugs-classification pull request #1
Opened 2020-03-20 12:35 UTC by SmirnovOleg

2020-03-23 13:54 UTC, ArtyomLobanov requested changes
Создал ветку deep-learning-approach. В следующий раз давай туда пул-реквесты делать https://github.com/ml-in-programming/bugs-classification/tree/deep-learning-approach

2020-03-23 13:54 UTC, ArtyomLobanov commented on python/app/model.py
> +        hidden = sum(weights.unsqueeze(-1) * gru_outs, dim=1)
Чтобы при чтении не возникало коллизий с родной функцией [sum](https://docs.python.org/3/library/functions.html#sum), лучше писать `torch.sum(...)`

2020-03-23 13:54 UTC, ArtyomLobanov commented on python/utils/scoring.py
> +    for sample_index in range(0, y.shape[0]):
Вроде в питоне принято по минимуму использовать циклы с явным счётчиком. 
```python
for predictions, target in zip(y_pred, y):
    most_probable_index = np.argmax(predictions)
```

2020-03-23 13:54 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/Hashers.java
> +    public static final HashExtractor<CodeChange.NodeState> TYPE_ONLY_NODE_STATE_HASH = HashExtractor.<CodeChange.NodeState>builder()
Очень длинные строки. 120 символов вроде нормой для java считается. Лучше заимпортить NodeState отдельно.
```java
import org.ml_methods_group.common.ast.changes.CodeChange.NodeState;
...
public static final HashExtractor<NodeState> TYPE_ONLY_NODE_STATE_HASH = HashExtractor.<NodeState>builder()
```

2020-03-23 13:54 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/KClosestPairsSelector.java
> +                        kClosestDistances.set(j, kClosestDistances.get(j - 1));
ArrayList удаляет последний элемент за О(1) и добавляет элементы в середину  за O(n). Чем целый отдельный цикл писать, проще было сделать так:
```java
if (kClosestDistances.get(i) > currentDistance) {
    kClosest.add(i, option);
    kClosest.remove(k);
    kClosestDistances.add(i, currentDistance);
    kClosestDistances.remove(k);
    break;
}
```
Ещё небось и быстрее получится т.к. ArrayList для сдвига части массива использует System.arraycopy

2020-03-23 13:54 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/KClosestPairsSelector.java
> +            final double currentDistance = metric.distance(value, option, Double.MAX_VALUE);
Тут, казалось бы, можно ` kClosestDistances.get(k-1)` передавать вместо `Double.MAX_VALUE`. Если у нас уже есть k элементов на расстоянии не более  `kClosestDistances.get(k-1)` , то элементы с большим или равным расстоянием нас не интересуют.

2020-03-23 13:54 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/KClosestPairsSelector.java
> +        System.out.println();
Дебаговый вывод

2020-03-23 13:54 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/ManyOptionsSelector.java
> +    int getKNearest();
От метода с названием `getKNearest` ожидаешь, что он вернёт тебе k каких-то объектов. Параметр k лучше отдавать через классический геттер `getK()`. Но тут возникает логичный вопрос: а что это за k такой-то? Откуда он взялся? Мне кажется, что тут нужно либо класс переименовать в KOptionsSelector, чтобы сразу заявить, что тут будет фигурировать некий параметр k, либо назвать метод более развёрнуто, без непонятных обозначений (например, getSelectionSize ).

2020-03-23 13:54 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/KClosestPairsSelector.java
> +    public KClosestPairsSelector(List<V> options, DistanceFunction<V> metric, int k_nearest) {
В java в SNAKE_CASE именуются только глобальный константы (`static final ...`). Локальные переменные, поля и аргументы именуются в camelCase с маленькой буквы, а классы в CamelCase с большой

2020-03-23 13:54 UTC, ArtyomLobanov commented on python/app/model.py
> +        # print(token_embeds.shape)
Такие комментарии лучше убирать, прежде чем что-то в репозиторий заливать

2020-03-23 13:54 UTC, ArtyomLobanov commented on python/classification.py
> +    data.make_tensors()
А зачем столько отдельных методов? Зачем разделять load, parse_tokens и make_tensors? Разбиение на test и validate лучше отдельно один раз сделать и сохранить. Да, сиды фиксируются, но если потом вдруг появится что-то, что использует генератор случайных чисел до чтения датасета, то всё разбиение поедет.

2020-03-23 13:54 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/PipelineEvaluation.java
> +        Path pathToTrain = datasetPath.resolve("__train_tokens_dataset.csv");
В чём отличие между этими двумя строками, что у доной стоит модификатор final, а у другой нет? Либо везде final ставь, либо нигде.

2020-03-23 13:54 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/PipelineEvaluation.java
> +        Path pathToTrain = datasetPath.resolve("__train_tokens_dataset.csv");
Кстати, раз другие два пути на зываются pathToX, то и datasetPath лучше обозвать pathToDataset. Ну, либо наоборот.

2020-03-23 13:54 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/MarkedClustersSaver.java
> +public class MarkedClustersSaver {
Класс называется как какая-то сущность, хотя на самом деле просто контейнер для статических методов.

2020-03-23 13:54 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetsCreator.java
> +        */
Опять же, эти комментарии в репозитории не нужны

2020-03-23 13:54 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetsCreator.java
> +            int tokensPerChange = 11;
Откуда взялось число 11? Какая-то магическая константа

2020-03-26 15:15 UTC, SmirnovOleg commented on python/classification.py
> +    data.make_tensors()
Объединил `load` и `parse_tokens` в инициализатор, с `dev_test_split` и `make_tensors` проблема - их можно делать только после отработки `parse_tokens`. Разбиение, кстати, не зависит от сидов, оно всегда делит на части в том порядке, как лежат данные в .csv, т.е. одинаково.

2020-03-26 15:19 UTC, SmirnovOleg commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetsCreator.java
> +            int tokensPerChange = 11;
Это то, сколько токенов через запятую запишет `fullExtractor` для одного `CodeChange`. Зависит это от внутренней структуры его хэшеров, в каком порядке там вписывать `.append(',')` внутри билдера. Но проблема в том, что это инкапсулировано, а пытаться применить этот экстрактор к какому-нибудь изменению и смотреть, сколько же запятых он там написал как-то невежливо :) Как быть?

2020-03-27 13:02 UTC, ArtyomLobanov requested changes

2020-03-27 13:02 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/Hashers.java
> +            .append(Character.toString(31))
А что тут случилось? Какие-то проблемы с кодировками? Пробовал явно везде прописывать, например, UTF-8?

2020-03-27 13:02 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetsCreator.java
> +            int tokensPerChange = 11;
Хотя бы в качестве параметра вынести на тот уровень, где ясно, какой конкретно будет хешер использоваться и сколько запятых он ставит. А вообще в идеале сразу генерировать желаемую последовательность токенов по Changes без использования хешеров. Тогда и костылей никаких не потребуется.

2020-03-27 13:02 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetsCreator.java
> +                        out.print(atomicCodeChangeTokens.replace((char)31, ',') + ",");
Так, я осознал, что 31 символ в ASCII ни разу не запятая.
![image](https://user-images.githubusercontent.com/9067686/77757945-3014a300-7043-11ea-817f-96df0cfb4aed.png)
Что вообще происходит?

2020-03-27 13:02 UTC, ArtyomLobanov commented on python/app/tokens_dataset.py
>          self.y_train = torch.LongTensor(self.df['cluster'].values)
Может лучше тогда просто [TensorDataset](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#TensorDataset) возвращать? Объекты, которые нужно как-то отдельно от конструктора инициализировать, не выглядят как что-то хорошее.

2020-03-29 07:36 UTC, SmirnovOleg commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetsCreator.java
> +                        out.print(atomicCodeChangeTokens.replace((char)31, ',') + ",");
Дело в том, что в токенах могут встречаться кавычки и запятые, но в CSV запятая - это разделитель, а двойные кавычки нужно писать два раза подряд. Т.к. потерять эти символы внутри токенов нестрашно, я их удаляю, но нельзя же удалять еще и запятые между токенами в одном `CodeChange`, поэтому там разделителем служит 31-й ASCII символ, `Unit Separator`, который потом снова заменится на запятые. Это костыль наверное, я вынесу тогда в статический метод отдельный у `Hashers`, как выше упоминалось

2020-04-02 10:41 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetsCreator.java
> +                        out.print(atomicCodeChangeTokens.replace((char)31, ',') + ",");
Неужели раньше никто не сталкивался с необходимостью экранирования символов в CSV файлах? Наверняка для этого уже написаны либы.

2020-04-02 11:00 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/Hashers.java
> +        return tokensPerChange.get(hasher);
Зачем плодить статические методы, если можно сделать это методом класса Hasher? Кажется, что каждый метод билдера добавляет контролируемое число запятых, кроме метода hashComponents, но если он используется, то в любом случае постоянство количества токенов не гарантируется. Можно какое-нибудь специальное значение добавить на этот случай.

2020-04-02 11:02 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/Hashers.java
>      public static final HashExtractor<NodeContext> full = HashExtractor.<NodeContext>builder()
static final константы именуются в SNAKE_CASE

2020-04-07 11:37 UTC, merged